// @USERS
export const GOT_CURRENT_USERS = "GOT_CURRENT_USERS";
export const ERR_CURRENT_USERS = "ERR_CURRENT_USERS";
export const ADD_USER = "ADD_USER";
export const UPD_USER = "UPD_USER";
export const REM_USER = "REM_USER";
export const ERR_USER = "ERR_USER";

// @PAGINTION OPTIONS
export const SET_USERS_OPTIONS = "SET_USERS_OPTIONS";

// @SAGAS PAGINATION
export const SET_PAGINATION_ASYNC = "SET_PAGINATION_ASYNC";

// @SAGAS USERS
export const FETCH_CURRENT_USERS = "FETCH_CURRENT_USERS";
